name: test

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - run: ls -al

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
